# Generated by Django 2.0.7 on 2018-07-28 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('price_small', models.DecimalField(decimal_places=2, max_digits=4)),
                ('price_large', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='SicilianPizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, unique=True)),
                ('price_small', models.DecimalField(decimal_places=2, max_digits=4)),
                ('price_large', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
