# Generated by Django 2.0.7 on 2018-07-29 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_regularpizza_sicilianpizza'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub',
            name='price_small',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4),
        ),
    ]
