# Generated by Django 2.0.7 on 2018-07-29 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20180729_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sub',
            name='price_small',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4),
        ),
    ]
