# Generated by Django 2.0.7 on 2018-07-31 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20180731_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(through='orders.Membership', to='orders.Item'),
        ),
    ]
