# Generated by Django 2.0.7 on 2018-07-31 16:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0011_auto_20180731_1621'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='user',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(blank=True, to='orders.Item'),
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
